### ISSUE TITLE
RouteTable to VPCEndpoint reference

### ISSUE THREAD

**Issue by kferrone** [crossplane/provider-aws#1036]
### What problem are you facing?

No ability to attach a VPCEndpoint to RouteTables routes. 

### How could Crossplane help solve your problem?

Make new VPCEndpoints a referenced gateway type of thing in the routes of RouteTable.

**Comment by haarchri** [comment]
at the end it is possible in VPCEndpoint via `routeTable`, `routeTableIdRef` or `routeTableIdSelector` https://github.com/crossplane/provider-aws/blob/master/apis/ec2/v1alpha1/custom_types.go#L295_L305

we get a route published in routeTabl from aws for vpc-endpoint with the following parameters:

```
      Gateway Id:             vpce-0955dfc529bfb7bf0
      Destination Prefix List Id:  pl-63a5400a
      State:                       active
```

if we want to add the `destionationPrefixListId`, `vpcEndpointId` in routeTable/v1beta1 to the inline routes we see that our functions for `lateInit`, `sortRoutes` needs updates otherwise we get a patch update here https://github.com/crossplane/provider-aws/blob/master/pkg/controller/ec2/routetable/controller.go#L224-L228
and the controller wants to remove the vpc-endpoint route with a error for `destinationCIDRBlock` here
https://github.com/crossplane/provider-aws/blob/master/pkg/controller/ec2/routetable/controller.go#L277-L297

so i remember the following issue: https://github.com/crossplane/provider-aws/issues/657

**provider-aws currently provides a RouteTable(v1beta1) with Routes defined in-line. At this time we cannot use a RouteTable with in-line routes in conjunction with Route(v1alpha1 - code-generated) resources or injected Routes from AWS like _VPCEndpoint_. Doing so will cause a conflict of rule settings and will overwrite/remove rules or provider-aws will stop with panic.**

_so my next idea:_

v1beta1:
- RouteTable with in-line routes https://doc.crds.dev/github.com/crossplane/provider-aws/ec2.aws.crossplane.io/RouteTable/v1beta1@v0.22.0

v1alpha1:
- Route https://github.com/crossplane/provider-aws/pull/859
- RouteTable (https://github.com/crossplane/provider-aws/pull/1037)

but RouteTable in v1alpha1 and v1beta1 in same setup looks not possible today ...

**Comment by haarchri** [comment]
added PR https://github.com/crossplane/provider-aws/pull/1084 to toggle the reconciliation of the routes array in routetable resource to reference for example routeTable with vpc-endpoint
