### ISSUE TITLE
Fail to delete a VPC if an EKS cluster was created in it

### ISSUE THREAD

**Issue by janwillies** [crossplane/provider-aws#142]
### What happened?
Created an EKS deployment incl corresponding infra resources and trying to delete it again. It's not possible to delete the VPC from crossplane, it hangs.

### How can we reproduce it?
1. Create a VPC with subnets, routetable, igw and iamrole. 
2. Create and delete an EKS cluster in this VPC
3. Delete the VPC and corresponding resources.
4. Everything will be deleted except the VPC, deleting hangs

```
    Message:               delete failed: failed to delete the VPC resource: DependencyViolation: The vpc 'vpc-01b02d8940effbbad' has dependencies and cannot be deleted.
                           status code: 400, request id: d6e70c68-c3b0-478c-82d5-2759c4078dda
    Reason:                Encountered an error during resource reconciliation
```
Manual deletion from AWS Console works fine and the vpc object disappears in crossplane

### What environment did it happen in?
Crossplane version: 0.8.0
AWS Stack: master from yesterday

**Comment by muvaf** [comment]
The root cause for this was a race condition regarding routetable and it has been fixed for quite a while now. If you experience this, feel free to reopen.

**Comment by rafaeldomi** [comment]
I can confirm this situation. The following scenario, all in one composition:
1. Create VPC, Subnets, IGW, NG
2. Create a Role for EKS, EKSCluster, NodeGroups, Addons: EBS CSI Driver, core-dns, Kubeproxy, VPC-CNI

When I remove this composition, take a while to all resources get removed (sometimes because of the race condition). But EKS create a Network Interface that is not known by crossplane, so the removal of the VPC get stuck  with the error that has dependencies.

Removing, manually, the ENI solves the problem.

How I would normally solve this?
Create a ENI in my composition and reference that resource in the EKS. But there isn't this field in the EKS Cluster.

What I NOT want to do?
To remove it manually, break the purpose of the automation.
