### ISSUE TITLE
Update IAMRolePolicyAttachment to refer IAMPolicy

### ISSUE THREAD

**Issue by sahil-lakhwani** [crossplane/provider-aws#232]
### What problem are you facing?

This `IAMRolePolicyAttachment` resource currently can refer to a IAM Policy in AWS by it's ARN. This issue is to update `IAMRolePolicyAttachment` so that it can refer to a IAM Policy in AWS voia an `IAMPolicy` resource in Crossplane.

### How could Crossplane help solve your problem?

There is already a resource in Crossplane called `IAMPolicy`. So, `IAMRolePolicyAttachment` can refer the `IAMPolicy` and use it's ARN (found as the value of `crossplane.io/external-name `aanotation).

**Comment by kferrone** [comment]
I was about to submit this same request. I can not reliably guess the ARN because of the account id in the ARN. 

Some solutions I have imagined for this issue:  
 - When referencing a policy, reference it exactly how a role is referenced. With a role you can choose from the following methods to reference: `roleName, roleNameRef, or roleNameSelector`.
 - if policy ARN omits the Account ID, then use the provider ref to inject it. Like: `arn:aws:iam:::policy/my-policy`
 - Or do what cloudformation does with variables in strings, e.g. `arn:aws:iam::${AWS::AccountId}:policy/my-policy`
 - if policy ARN is undefined when submitted to crossplane, then have crossplane use an IAMPolicy object with the same name as the referenced role and/or the IAMRolePolicyAttachment

**Comment by muvaf** [comment]
I took a stab at this in https://github.com/crossplane/provider-aws/pull/257

@kferrone The way the referencers work is that we supply [a custom `func`](https://github.com/crossplane/provider-aws/pull/257/files#diff-053411cd6b4857d12788c7944658461bR59) to get any value from the struct. In this case, we get the policy ARN from `status.atProvider` which is the exact representation of what AWS returns for `Describe` call. So, I'd expect all policy ARN inputs to be compatible with that output. During my manual test, I saw that the ARN in `status.atProvider` field of `IAMPolicy` does include the account ID, so it should be good to go.
