### ISSUE TITLE
manage policies of KMS key

### ISSUE THREAD

**Issue by janwillies** [crossplane/provider-aws#319]
### What problem are you facing?
We would like to manage policies of an existing KMS key, so that IAM-Roles are able to use that key for encryption of AWS resources

### How could Crossplane help solve your problem?
Crossplane would update the `Principal` with the new IAM-Role. E.g. implement `PutKeyPolicy` from https://docs.aws.amazon.com/sdk-for-go/v2/api/service/kms/#Client.PutKeyPolicyRequest

Example policy:
```yaml
{
    "Version": "2012-10-17",
    "Id": "key-consolepolicy-3",
    "Statement": [
        {
            "Sid": "Allow use of the key",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::1234567890:role/ebs-csi-iam-role"
                ]
            },
            "Action": [
                "kms:Encrypt",
                "kms:Decrypt",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*",
                "kms:DescribeKey"
            ],
            "Resource": "*"
        },
        {
            "Sid": "Allow attachment of persistent resources",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::1234567890:role/ebs-csi-iam-role"
                ]
            },
            "Action": [
                "kms:CreateGrant",
                "kms:ListGrants",
                "kms:RevokeGrant"
            ],
            "Resource": "*",
            "Condition": {
                "Bool": {
                    "kms:GrantIsForAWSResource": "true"
                }
            }
        }
    ]
}
```

**Comment by muvaf** [comment]
We synced with @janwillies and Hendrik offline. I'll write a summary here for future reference.

The use case is some kind of aggregation similar to `IAMRolePolicyAttachment` where you have N `IAMRolePolicyAttachment`s to 1 `IAMRole`. However, in KMS case, there is only 1 Key Policy in AWS API and it can only be added via `PutKeyPolicy`. So, we'll move forward with implementing `kind: Key, apiVersion:kms.aws.crossplane.io` full CRD and it'll have a JSON blob field for Key Policy.

As an addition, a small controller outside of Crossplane will have its own CRD that has a role reference and `Principal` to add to the referenced Key Policy. That controller will just gather CRs, produce the final policy JSON blob and update `Key` CR. Then Crossplane AWS Provider will make the necessary calls to update the Key Policy of the Key.

It's possible to say that this small controller could just call the AWS API but interacting with Crossplane CR is easier in terms of implementation and also authentication and other features are already implemented & maintained in AWS Provider so that additional controller will be very small and specific for their use case. Open to alternative suggestions.

**Comment by muvaf** [comment]
Closing in favor of https://github.com/crossplane/provider-aws/issues/357 . @janwillies feel free to reopen if you think that issue doesn't cover what needs to be done for that use case.
