### ISSUE TITLE
Provider AWS failed to start without Crossplane

### ISSUE THREAD

**Issue by krishchow** [crossplane/provider-aws#371]
### What happened?

When I attempt to start the AWS provider using go build and running the binary, it begins loading of the controller, but after around 30 seconds it stops with the following errors
1. `2020-10-07T12:39:05.225-0400    ERROR   controller-runtime.source       if kind is a CRD, it should be installed before calling Start   {"kind": "KubernetesTarget.workload.crossplane.io", "error": "no matches for kind \"KubernetesTarget\" in version \"workload.crossplane.io/v1alpha1\""}`
2. `go_build_main_go: error: Cannot start controller manager: [no matches for kind "KubernetesTarget" in version "workload.crossplane.io/v1alpha1", failed waiting for all runnables to end within grace period of 30s: context deadline exceeded]`

If I install Crossplane prior to running the Provider-AWS, there is no error, but I believe you should be able to run the Provider-AWS independently. 

### How can we reproduce it?

1. Create a new Kubernetes cluster, I am using Kind.
2. Install all of the CRDs from under /package/crds
3. Build the binary for the Provider-AWS and run with the --debug flag

### What environment did it happen in?

Provider-AWS version: master
Crossplane version: N/A
kind version: 0.8.1
Kubernetes version: v1.18.3
OS: Fedora 31

**Comment by muvaf** [comment]
I believe installing a provider with Crossplane enables the following features:
* Necessary `ClusterRole`s for `provider-aws-controller` pod.
* `ClusterRole`s necessary for Crossplane to create provider-aws resources in compositions.
* Installation of AWS CRDs.
* Upgrade/Rollback support.
* Dependency resolution (not yet implemented)

and some things I don't recall right now. In essence, providers are meant to be installed via Crossplane Package Manager so it's unlikely that we'll make changes here to make it work. However, if you're looking to run it in development with `cluster-admin` capabilities and without composition, the only problem you'll encounter is that last bit of dependency we have, `KubernetesTarget`, in providers. In the next release, that type will be removed, so provider-aws will be able to run without its CRD installed. 

Though keep in mind that it's very unlikely that we'll have an alternative mode where you can feasibly run provider-aws in prod or critical env without Crossplane because the existing method integrates many features of Crossplane ecosystem and we'd need very good reasons to be convinced to maintain another path of installation of providers.

**Comment by hasheddan** [comment]
@krishchow note that for dev, you can just run `kubectl apply -k https://github.com/crossplane/crossplane//cluster?ref=master` before running controller and you should be good to go :slightly_smiling_face:

**Comment by krishchow** [comment]
@muvaf - is the removal of the KubernetesTarget on the roadmap for v0.13? I created this issue to mainly focused on the development/testing phase of the provider-aws specifically where it would be nice for the provider to run standalone. 
@hasheddan - thanks for clarifying! I'll try that out

**Comment by muvaf** [comment]
> is the removal of the KubernetesTarget on the roadmap for v0.13?

@krishchow no, we deprecated it in 0.13 and will remove in 0.14
