### ISSUE TITLE
AWS WordPress example: resources cannot be cleaned up, because of orphan resources

### ISSUE THREAD

**Issue by soorena776** [crossplane/provider-aws#40]
### What happened?

After installing WordPress example, when cleaning up the resource connectivity resources, deleting some resources fail because they depend on resources that are created directly by Kubernetes Application. For instance, the application automatically creates a [ELB](https://aws.amazon.com/elasticloadbalancing/) load balancer, hence blocking the deletion of the `VPC`resource

### How can we reproduce it?

- Follow the WordPress workload example and install it
- Remove the resources by running `kubectl delete -f <directory>`

### What environment did it happen in?
Crossplane version: v0.3

-----
Update:
-----
I confirmed that if the `KubernetesApplication` is deleted before deleting `EKSCluster`, this problem won't happen.

**Comment by negz** [comment]
My guess is the issue here is to do with the relationship between the `KubernetesApplication` and the `KubernetesCluster` it was scheduled to.

My recollection is that if the `KubernetesApplicationResource` controller is trying to delete a `KubernetesApplicationResource` but finds it can't connect to its scheduled `KubernetesCluster` because it no longer exists it assumes there's nothing that can be done, and considers the `KubernetesApplication` deleted. So I'm guessing what's happening here is.

1. Deploying the `KubernetesApplication` creates an ELB in the `VPC` the `EKSCluster` bound to the scheduled `KubernetesCluster`.
1. When deleting everything all at once the `KubernetesCluster` happens to get deleted before the `KubernetesApplication`, so it has no way of deleting its `KubernetesApplicationResources` - they keep running. The `EKSCluster` itself is deleted, but nothing cleans up its services (and thus ELBs). 
1. We now can't delete the `VPC` because there are orphaned ELBs in it.

**Comment by muvaf** [comment]
This is irrelevant since these CRDs are removed now.
