### ISSUE TITLE
duplication: RouteTable is also used to create Routes

### ISSUE THREAD

**Issue by Dkaykay** [crossplane/provider-aws#657]
### What happened?
As discussed with @muvaf via Slack:

**RouteTable** encapsulates **Route** creation ([source](https://github.com/crossplane/provider-aws/blob/master/pkg/controller/ec2/routetable/controller.go#L299)), which is not a wanted feature. 
It should be possible to create RouteTables and Routes independently. 

This also seems to conflict with CPs aim for [high fidelity](https://github.com/crossplane/crossplane/blob/master/design/one-pager-managed-resource-api-design.md#high-fidelity) representation of the provider API.

References:

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateRouteTable.html
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateRoute.html

### How can we reproduce it?
Try to create a route in an existing routetable

### What environment did it happen in?
Crossplane version: 1.2.0
provider-aws: 0.18

**Comment by muvaf** [comment]
I think we had had this discussion with @hasheddan but I couldn't find it now. I agree that having [`Route`](https://github.com/crossplane/provider-aws/blob/b8f8842/pkg/controller/ec2/routetable/controller.go#L337), [`RouteTable`](https://github.com/crossplane/provider-aws/blob/b8f8842/pkg/controller/ec2/routetable/controller.go#L165) and [`RouteTableAssociation`](https://github.com/crossplane/provider-aws/blob/b8f8842/pkg/controller/ec2/routetable/controller.go#L391) CRDs would be better rather than having it all in `RouteTable`.

It seems Terraform has `aws_route`, `aws_route_table` and `aws_route_table_association` but `aws_route_table` has optional list of `aws_route`s as well. See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route_table

**Comment by Dkaykay** [comment]
If you want, we could try to split up the resources.
Would this introduce a breaking change? How do you usually handle such changes? @muvaf

**Comment by muvaf** [comment]
@Dkaykay I think we'd keep `RouteTable` as is for a while until it's `v1` and implement the additional resources.

@hasheddan thoughts about this issue?

**Comment by hasheddan** [comment]
Hmm I would tend to agree that we don't want to break the API contract here. However, I was hoping we could just make the routes optional in `RouteTable` so that someone could either use them (current functionality), or use a new `Route` resource directly. This is not straightforward though because I presume the `RouteTable` would attempt to delete any `Route` that was not defined in its inline slice, thus causing thrashing between the controllers. A few thoughts:
- Webhook support in core crossplane could help us migrate this to a new version
- One option in the short term could be to say if _no routes are defined on `RouteTable`_ then the user is essentially opting out of route management and deferring it to individual `Route` instances. This has its own set of problems and unexpected behavior, so we should carefully consider if this issue is critical enough to warrant a change like that.

**Comment by muvaf** [comment]
> One option in the short term could be to say if no routes are defined on RouteTable then the user is essentially opting out of route management and deferring it to individual Route instances.

@hasheddan We could add a field like `ignoreRoutes: true` to toggle the reconciliation of the routes array. Existing users wouldn't be affected and new users of `RouteTable` would set this to `false` and use `Route` objects. We'd drop this field altogether in `apiVersion: v1` of `RouteTable`

**Comment by haarchri** [comment]
since @Dkaykay  and me provided EC2-Route with #859 we need an option for future - think approach from @muvaf looks okay for me

**Comment by haarchri** [comment]
added a PR for the toggle https://github.com/crossplane/provider-aws/pull/1084 and tested it with vpc-endpoint resource

**Comment by haarchri** [comment]
implemented with https://github.com/crossplane/provider-aws/pull/1084
