### ISSUE TITLE
VPC endpoints support for aws provider

### ISSUE THREAD

**Issue by mqxter** [crossplane/provider-aws#715]
Currently there is no support for vpc endpoints (s3, ecr kms etc). 
Clusters that reside in private/local subnets need a connection to aws services in order to pull/push docker images(ecr), use s3 or kms without going through the internet. 

v0.18.1

**Comment by dare-darryl** [comment]
VPC Endpoint support will be useful for me as well.

For my use case, I have private resources scattered across several AWS Accounts/VPCs that I would like to connect to from my cluster. As such, I would like to be able to create a VPC endpoint resource from my cluster, so that my cluster will be able to hit those resources.

Will be happy to contribute to this if this is not already in the works.

**Comment by Dkaykay** [comment]
Related:
VPC Peering Connections might be supported soon, see https://github.com/crossplane/provider-aws/pull/689

**Comment by dare-darryl** [comment]
Starting work on VPC Endpoint. 
Objective: create a VPC Endpoint object from Crossplane.

**Comment by yogeek** [comment]
Are VPC endpoint service and interface endpoint [documented here](https://docs.aws.amazon.com/vpc/latest/privatelink/endpoint-service-overview.html) going to be included in this on going work please ?

By this I mean : today we are creating these 2 resources with Terraform (1 [VPC Endpoint Interface](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint#interface-endpoint-type) linked to 1 [VPC Load Balancer Endpoint Service](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint_service#network-load-balancers)) in order to provide internal access to the LB of an Istio ingress gateway and as this must happen after istio deployment, we would prefer to do it with Crossplane + gitops:

EC2 --> VPC Endpoint (in VPC1) --> VPC Endpoint Service (in VPC2) --> NetworkLoadBalancer --> EC2

**Comment by dare-darryl** [comment]
At the moment no. I'm not planning for VPC Endpoint Service.
