### ISSUE TITLE
KMS Keys do not delete immediately, but the resource should

### ISSUE THREAD

**Issue by AaronME** [crossplane/provider-aws#849]
### What happened?
KMS keys do not immediately get deleted from AWS. Instead they enter a "pending deletion" state. There is a mandatory waiting period that cannot be shorter than 7 days or longer than 30 days.

Once a key is scheduled for deletion, provider-aws should delete the Resource.

"Restoring" the key can be accomplished by recreating the Resource with an `external-name` annotation.

### How can we reproduce it?
1. Create a KMS key
2. Delete the key
3. The resource will be "pending" deletion for the entire waiting period.

### What environment did it happen in?
Crossplane 1.4
provider-aws 1.19+ (master)

**Comment by haarchri** [comment]
also wanted to open this bug because we see in one of our test aws-accounts that a single kms key in pending deletion makes a huge number of KMS API calls  

![image](https://user-images.githubusercontent.com/21083497/135577523-eccf9fc2-178c-48c9-b03c-28f436e427d7.png)


https://github.com/crossplane/provider-aws/issues/847

**Comment by haarchri** [comment]
@muvaf ist this fixed with https://github.com/crossplane/provider-aws/pull/950/files#diff-bf2cae20a0f8a925bf569f32f5f90112555712cd9013bb4f924b25d08b0643f0R75 ?

**Comment by muvaf** [comment]
@haarchri yes, it is fixed with that PR. Thanks for checking!
