### ISSUE TITLE
Add support for Amazon EC2 Instances

### ISSUE THREAD

**Issue by displague** [crossplane/provider-aws#85]
### What problem are you facing?

Since MachineInstance was implemented in https://github.com/crossplaneio/crossplane/pull/942 in support of https://github.com/crossplaneio/crossplane/issues/286, https://github.com/packethost/stack-packet remains the only provider to implement this claim kind.

### How could Crossplane help solve your problem?

EC2 VM Instances should be supported for abstracting MachineInstance resources between providers.

**Comment by milindchawre** [comment]
+1
Eagerly waiting for this feature. Just imagining what all cool things can be built once its implemented.m

**Comment by afritzler** [comment]
@milindchawre same here! Machine instances + keypairs + EBS volumes + volume mounts would be pretty dope! 😎

**Comment by muvaf** [comment]
I just tested whether this could be achieved by [ACK code generation](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md). But it seems like AWS API named instance creation command as `RunInstances` instead of `CreateInstances`, which causes ACK not to recognize it as a resource. However, a lot of EC2 resource are recognized, like key pairs volumes etc. So, if anyone is interested, you all are welcome to contribute with t[his new and much easier process](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md) to add a new resource 🙂

**Comment by surenraju** [comment]
It will be really awesome if we are able to create EC2 instance! Eagerly waiting for this feature!!

**Comment by JAditya1395** [comment]
Hi All, So its been quite a while since the last comment on this thread. I am still very curious and excited for this feature but unfortunately i can not find anything conclusive. Is there a dedicated timeline for its support because it will be super helpfuil

**Comment by jbw976** [comment]
Thanks for weighing in on this issue @JAditya1395 and @surenraju! 

@tnthornton has started working on this issue and has a draft PR open in https://github.com/crossplane/provider-aws/pull/777 🎉

**Comment by JAditya1395** [comment]
@jbw976 Thanks for the acknowledgement. 
@tnthornton Great work Taylor. I am looking forward to this feature. I can see this i still a WIP but do we have any rough timeline where we can see this feature in the near future.

**Comment by tnthornton** [comment]
>I can see this i still a WIP but do we have any rough timeline where we can see this feature in the near future.
FWIW, I just moved the PR out of draft state. I'll keep a close eye on PR comments so we can keep this moving along.
