### ISSUE TITLE
Rename of IAM resources

### ISSUE THREAD

**Issue by muvaf** [crossplane/provider-aws#989]
### What problem are you facing?

We have `IAMUser`, `IAMGroup` etc. in `identity.aws.crossplane.io` group. However, the convention we use for other resources require those to be named as `User`, `Group` and in `iam.aws.crossplane.io`.

### How could Crossplane help solve your problem?

We can create correctly named versions of these resources and deprecate the old ones, similar to how we are in process of moving `RDSInstance` in `database` group to `DBInstance` in `rds` group.

**Comment by muvaf** [comment]
For `v1beta1` ones: We can have the new ones as completely independent types and controllers to give users time to migrate.
For `v1alpha1` ones: we can remove their controller so that only the new ones are reconciled and old ones aren't deleted.

**Comment by smcavallo** [comment]
Would it make sense to merge iam `v1alpha` resources into `v1beta1` as part of this?  `IAMRole` is part of `identity/v1beta1` package and `IAMPolicy` is part of `identity/v1alpha1` package.
`identity/v1beta1` already depends on `identity/v1alpha1` If a reference resolver (in `identity/v1alpha1`) is added for `IAMRole` (from `identity/v1beta1` it creates a circular dependency.  
It would be helpful from both a consumer point of view and codewise for all iam resources to live in the same API version, especially since the policy resources have been in alpha for so long.

Additionally, what about autogenerating these resources if the api will be changing anyways?  From a consumer point of view we prefer using autogenerated resources over the manually generated ones, and would prefer that for any api change.

**Comment by muvaf** [comment]
> Would it make sense to merge iam v1alpha resources into v1beta1 as part of this?

That is what I'm aiming to do actually and this is probably the only blocker.

> Additionally, what about autogenerating these resources if the api will be changing anyways?

**Comment by muvaf** [comment]
I'm planning to move forward with this proposal in order for it to land in the next minor release, which is on December 14, 2021.
